### PR TITLE
POST /login endpoint

### LINKED ISSUE #764: Consider a POST /login endpoint
See the idea [in this comment](https://github.com/rabbitmq/rabbitmq-management/pull/748#issuecomment-564458397).

After the "automagical" client-side login path was removed, the only zero effort login option for hosted RabbitMQ providers is OAuth 2, which can take a fair amount of effort to integrate.

It would be easier if we had a `POST /login` endpoint that would authenticate and set a cookie in response. It would make it easy to develop a tiny custom login page as a stop-gap measure.

### PR DESCRIPTION
**Pull request by dcorbacho**
Closes #764

## Types of Changes
- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the
discussion by explaining why you chose the solution you did and what
alternatives you considered, etc.

### CODE REVIEW

**Comment by lukebakken** [comment]
Testing this now

**Comment by lukebakken** [comment]
Tested like this with `curl`:

```
curl -4vvv -c "$HOME/curl_cookies.txt" -H 'content-type: application/x-www-form-urlencoded' --data 'username=guest&password=guest' localhost:15672/api/login

curl -4H 'Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=' localhost:15672/api/whoami
```

**Comment by lukebakken** [comment]
Backported to `v3.8.x` and `v3.7.x`

**Comment by lukebakken** [comment]
Follow-up commit to fix the `cors_test` test:

https://github.com/rabbitmq/rabbitmq-management/commit/4141e491c30aba685257ae19c14de3780d4ffbb1

**Comment by acogoluegnes** [comment]
@dcorbacho @lukebakken This kinda works with `httpie`:

```
http --form POST http://localhost:15672/api/login username=guest password=guest 
HTTP/1.1 415 Unsupported Media Type
content-length: 0
content-security-policy: default-src 'self'
date: Thu, 23 Jan 2020 08:07:10 GMT
server: Cowboy
set-cookie: auth=Z3Vlc3Q6Z3Vlc3Q=; Version=1
vary: accept, accept-encoding, origin
```

It's because `httpie` send the following header, which our REST handler is not happy with:

```
Content-Type: application/x-www-form-urlencoded; charset=utf-8
```

This can be solved by the following:

```erlang
content_types_accepted(ReqData, Context) ->
  {[{{<<"application">>, <<"x-www-form-urlencoded">>, '*'}, accept_content}], ReqData, Context}.
```

What do you think? I don't think it does any harm to be more permissive with content type parameters.

Then with `httpie`:

```
http --form POST http://localhost:15672/api/login username=guest password=guest
HTTP/1.1 200 OK
cache-control: no-cache
content-length: 4
content-security-policy: default-src 'self'
content-type: application/json
date: Thu, 23 Jan 2020 08:10:03 GMT
server: Cowboy
set-cookie: auth=Z3Vlc3Q6Z3Vlc3Q=; Version=1
vary: accept, accept-encoding, origin

"ok"
```

Still working with `curl`:

```
curl -v -d "username=guest&password=guest" -H "Content-Type: application/x-www-form-urlencoded" http://localhost:15672/api/login 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15672 (#0)
> POST /api/login HTTP/1.1
> Host: localhost:15672
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 29
> 
* upload completely sent off: 29 out of 29 bytes
< HTTP/1.1 200 OK
< cache-control: no-cache
< content-length: 4
< content-security-policy: default-src 'self'
< content-type: application/json
< date: Thu, 23 Jan 2020 08:11:18 GMT
< server: Cowboy
< vary: accept, accept-encoding, origin
< set-cookie: auth=Z3Vlc3Q6Z3Vlc3Q=; Version=1
< 
* Connection #0 to host localhost left intact
"ok"%          
```
With incorrect password:
```
curl -v -d "username=guest&password=badpassword" -H "Content-Type: application/x-www-form-urlencoded" http://localhost:15672/api/login
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15672 (#0)
> POST /api/login HTTP/1.1
> Host: localhost:15672
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 35
> 
* upload completely sent off: 35 out of 35 bytes
< HTTP/1.1 401 Unauthorized
< content-length: 50
< content-security-policy: default-src 'self'
< content-type: application/json
< date: Thu, 23 Jan 2020 08:11:48 GMT
< server: Cowboy
< vary: origin
< 
* Connection #0 to host localhost left intact
{"error":"not_authorised","reason":"Login failed"}%
```

**Comment by dcorbacho** [comment]
@acogoluegnes I think being more permissive is fine

**Comment by lukebakken** [comment]
Good catch. I should start testing with `charset`.

**Comment by lukebakken** [comment]
@acogoluegnes @dcorbacho I'll make the change.

**Comment by lukebakken** [comment]
💥 https://github.com/rabbitmq/rabbitmq-management/commit/6754ddc58260f962da2bb3adfdbed5580cf84543

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-management/commit/4141e491c30aba685257ae19c14de3780d4ffbb1 and https://github.com/rabbitmq/rabbitmq-management/commit/6754ddc58260f962da2bb3adfdbed5580cf84543 backported to `v3.8.x` and `v3.7.x`

**Pull request merged**
