### PR TITLE
Switch test suite to Common Test

### LINKED ISSUE #218: Migrate test suite to Common Test
With `rabbit` and `rabbit_common` test suites and helpers upgraded to Common Test earlier, I have test suite terminations for both master and stable:

```
rabbit_mgmt_test_clustering
---------------------------
cluster_nodes: [setup]undefined
*unexpected termination of test process*
::{exit_status,1,
               [0,137],
               "{error_logger,{{2016,6,6},{12,32,50}},\"Protocol: ~tp: not supported~n\",[\"inet_proxy\"]}\r\n{error_logger,{{2016,6,6},{12,32,50}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.23.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[<0.20.0>]},{dictionary,[{longnames,false}]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,170}],[]]}\r\n{error_logger,{{2016,6,6},{12,32,50}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{id,net_kernel},{mfargs,{net_kernel,start_link,[[a,shortnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}\r\n{error_logger,{{2016,6,6},{12,32,50}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{id,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}\r\n{error_logger,{{2016,6,6},{12,32,50}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,\"application_master.erl\"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}\r\n{error_logger,{{2016,6,6},{12,32,50}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}\r\n{\"Kernel pid terminated\",application_controller,\"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}\"}\r\n\r\nCrash dump is being written to: erl_crash.dump...done\r\nKernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k\r\n"}

=======================================================
  Failed: 0.  Skipped: 0.  Passed: 0.
One or more tests were cancelled.
/home/antares/git/stable_umbrella.git/deps/rabbit_common/mk/rabbitmq-tests.mk:64: recipe for target 'standalone-tests' failed
make: *** [standalone-tests] Error 1
```

Background nodes seem to be started with an incorrect set of arguments. This also affects federation and a few other plugins, so I strongly suspect the issue is in the test helpers that manage nodes.

### PR DESCRIPTION
**Pull request by michaelklishin**
Fixes #218.

Note: this intentionally deletes several tests that depend on ETS
table state and clash with "real" stats GC processes running in parallel.
Some of them are covered in other test suites, e.g. [rabbit-hole](https://github.com/michaelklishin/rabbit-hole), others
can only really be tested with a separate simulation test suite.

Per discussion with the team.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Also note: https://github.com/rabbitmq/rabbitmq-management/issues/234.

**Comment by kjnilsson** [comment]
Tests work well and looks good to me. @michaelklishin we should probably squash a few commits before merging. Happy to do that if you like.

**Comment by michaelklishin** [comment]
@kjnilsson feel free to do it.

**Comment by michaelklishin** [comment]
actually, let me squash and re-push

**Comment by michaelklishin** [comment]
Will squash and merge into stable locally, per discussion with @kjnilsson.

**Comment by michaelklishin** [comment]
Done in https://github.com/rabbitmq/rabbitmq-management/commit/cd22afa878c62c13d328c07743bd5a307473149d.

**Comment by michaelklishin** [comment]
Done in `stable`, now merging into master.

**Pull request closed without merging**
