### PR TITLE
Allow normal https connections in rabbitmqadmin again

### LINKED ISSUE #299: rabbitmqadmin not backward compatible with older server versions
Using rabbitmqadmin 3.6.4 querying a 3.5.7 server will result in: 

```
Traceback (most recent call last):
  File "/usr/local/sbin/rabbitmqadmin", line 1007, in <module>
    main()
  File "/usr/local/sbin/rabbitmqadmin", line 413, in main
    method()
  File "/usr/local/sbin/rabbitmqadmin", line 592, in invoke_show
    format_list('[{0}]'.format(self.get(uri)), cols, obj_info, self.options)
  File "/usr/local/sbin/rabbitmqadmin", line 436, in get
    return self.http("GET", "%s/api%s" % (self.options.path_prefix, path), "")
  File "/usr/local/sbin/rabbitmqadmin", line 475, in http
    self.options.port)
  File "/usr/local/sbin/rabbitmqadmin", line 451, in __initialize_https_connection
    context = self.__initialize_tls_context())
  File "/usr/local/sbin/rabbitmqadmin", line 467, in __initialize_tls_context
    self.options.ssl_key_file)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Is that a known limitation?

### PR DESCRIPTION
**Pull request by carlhoerberg**
Fixes #299, a bug introduced by #151

### CODE REVIEW

**Comment by michaelklishin** [comment]
@carlhoerberg was this meant to be submitted against `stable`?

**Comment by michaelklishin** [comment]
This can (and should) be backported to `stable`.

**Comment by carlhoerberg** [comment]
ok! should i open a new PR against that branch?

**Comment by michaelklishin** [comment]
I will cherry-pick. Thank you.

**Pull request merged**
