### PR TITLE
Add link to Management Stats doc

### PR DESCRIPTION
**Pull request by gerhard**
I found it most useful while working on rabbitmq_prometheus, I think
others will appreciate knowing about it too. There was no link to it on
management, there is a single reference to this document on the website,
introduced in #427.

* https://github.com/rabbitmq/rabbitmq-website/blame/433eec2476ca691616efc17d5dc0bd3abe9bb8be/site/monitoring.md#L227

image

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by michaelklishin** [comment]
I don't find HTTP stats to be descriptive. There is a link to that page from `/api/index.html`. I 👎 this proposal.

**Comment by michaelklishin** [comment]
Perhaps the stats page can be folded into the main HTTP API doc guide with a redirect for backwards compatibility.

**Comment by michaelklishin** [comment]
See #697 for what I'd do.

**Comment by gerhard** [comment]
I like #697 more too.

**Pull request closed without merging**
