### PR TITLE
reduces the wasted space in the console

### PR DESCRIPTION
**Pull request by sc-chad**
## Proposed Changes

Tightens up the columns while giving better readability and reduces wasted space

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the mailing list. We're here to help! This is simply a reminder
of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

Was unable to run tests but is such a small cosmetic change I think we'll be okay.

Before:
screen shot 2018-01-11 at 10 13 38 am

After:
screen shot 2018-01-11 at 10 09 29 am

### CODE REVIEW

**Comment by michaelklishin** [comment]
It would be much easier to accept such a PR if screenshots of the same page before and after the change were posted.

**Comment by sc-chad** [comment]
@michaelklishin Done.  Sorry about that, was working on doing so when you commented.

**Comment by michaelklishin** [comment]
Thanks, this change seems like an improvement to me. @rabbitmq/core WDYT?

**Comment by lukebakken** [comment]
I'm going to check with various screen widths.

**Comment by carlhoerberg** [comment]
reducing the height of the tbody rows is ok, but removing _all_ padding in the thead cells does not look an improvement to me

**Comment by carlhoerberg** [comment]
to get the desired effect i believe you could "just" decrease the the padding of the badges ("+2" in the screenshot above)

**Comment by gerhard** [comment]
How does this change affect lines that wrap?

image

What about stacked `abbr` & `input` elements?

image

**Comment by lukebakken** [comment]
@gerhard I had the same thought, too. A while back I made what I thought were appropriate padding changes that didn't work when elements were wrapped like you show.

**Comment by sc-chad** [comment]
Updated:

screen shot 2018-01-11 at 10 48 01 am

screen shot 2018-01-11 at 10 48 01 am

**Comment by michaelklishin** [comment]
Note that @gerhard uses a different table — that of cluster nodes — above.

**Comment by gerhard** [comment]
Nodes list **with** `vertical-align: top`
screen shot 2018-01-11 at 17 14 16

Nodes list **without** `vertical-align: top`
screen shot 2018-01-11 at 17 14 47

Which tables does not having `vertical-align: top` help?

**Comment by sc-chad** [comment]
@gerhard Leaving vertical:top causes additional padding on the bottom of the row in the queues table.  This causes them to feel misaligned.

Example:

screen shot 2018-01-11 at 11 22 01 am

**Comment by gerhard** [comment]
Nodes list `2px` padding:
screen shot 2018-01-11 at 17 17 56

Nodes list `5px` padding:
screen shot 2018-01-11 at 17 18 33

Even though the smaller padding helps fit 17% more rows (30 vs 25), to me the content seems too tightly packed. What do others think?

25 connections at `5px`:
screen shot 2018-01-11 at 17 23 52

30 connections at `2px`:
screen shot 2018-01-11 at 17 23 20

**Comment by michaelklishin** [comment]
I personally like the 30 connections version but not the way vertical alignment makes that particular table in https://github.com/rabbitmq/rabbitmq-management/pull/541#issuecomment-357001429.

**Comment by sc-chad** [comment]
I updated the PR to 2px: https://github.com/rabbitmq/rabbitmq-management/pull/541/commits/5bc8639eb8bb3cb648dae10014615279aeab18f9

**Comment by gerhard** [comment]
OK, happy to keep the `2px` padding.

Since the `vertical-padding: top` removal makes the nodes table look misaligned, I am wondering whether we should restrict this change only to the tables that it benefits, such as the queues table. What do you think @sc-chad ?

**Comment by sc-chad** [comment]
@gerhard I think this will get us there. Needs double checked on smaller resolutions.  

The end result is:
- 2px padding on top and bottom reduced from 5x
- vertical alignment set to middle for the table contents

**Comment by gerhard** [comment]
I can still see in your latest screenshots that `div.updatable>table.list td { vertical-align: middle; }` still affects alignment in the nodes table.

Given all the conversations that we've had so far, I see the following options:

1. Continue discussing and iterating on the `vertical-align: middle` until we get it right
1. Restrict this PR to just the `table th, table td { font: 12px Verdana, sans-serif; padding: 2px 4px; }` change and benefit from the existing consensus

What do others think?

**Comment by sc-chad** [comment]
Removed any alignment changes and broke out the padding to not add additional padding on the bottom.

Hopefully this gets us there :)

screen shot 2018-02-05 at 12 17 15 pm
screen shot 2018-02-05 at 12 17 08 pm

**Comment by michaelklishin** [comment]
The super tight spacing on the node list page is ugly and doesn't seem to be necessary. You usually don't see 100 nodes, so why should that table change at all?

**Comment by sc-chad** [comment]
@gerhard Done.  Thanks guys!

**Comment by sc-chad** [comment]
haha was my pleasure thanks guys.

**Comment by michaelklishin** [comment]
Backported to 3.7.x and 3.6.x.

**Comment by michaelklishin** [comment]
This was backported to `3.6.16`.

**Pull request merged**
