### PR TITLE
rabbitmqadmin: only call maybe_utf8 if val is not None

### LINKED ISSUE #568: rabbitmqadmin: AttributeError: 'NoneType' object has no attribute 'encode'
The below command throws **AttributeError: 'NoneType' object has no attribute 'encode'**:

```
./rabbitmqadmin --username=username --password=password  -f long -d 3 list queues
```

```
Traceback (most recent call last):
  File "./rabbitmqadmin", line 1063, in <module>
    main()
  File "./rabbitmqadmin", line 447, in main
    method()
  File "./rabbitmqadmin", line 638, in invoke_list
    format_list(self.get(uri), cols, obj_info, self.options)
  File "./rabbitmqadmin", line 761, in format_list
    formatter_instance.display(json_list)
  File "./rabbitmqadmin", line 772, in display
    (columns, table) = self.list_to_table(json.loads(json_list), depth)
  File "./rabbitmqadmin", line 826, in list_to_table
    add('', 1, item, add_to_row)
  File "./rabbitmqadmin", line 805, in add
    fun(column, subitem)
  File "./rabbitmqadmin", line 812, in add_to_row
    row[column_ix[col]] = maybe_utf8(val)
  File "./rabbitmqadmin", line 468, in maybe_utf8
    return s.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

We've fixed it locally by updating the _add_to_row_ function to only call _maybe_utf8_ if val is not None:

```
        def add_to_row(col, val):
            if col in column_ix:
                if val: row[column_ix[col]] = maybe_utf8(val)
```

### PR DESCRIPTION
**Pull request by pjmyburg**
Closes #568

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pjmyburg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-management&pullRequestId=569)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-management&pullRequestId=569) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pjmyburg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-management&pullRequestId=569)!

**Comment by pjmyburg** [comment]
Tests are now failing for OTP 19.3, but it doesn't seem to be related?  Passing for OTP 20.3

**Comment by michaelklishin** [comment]
No, doesn't seem to be. Travis containers must have even fewer resources than our Concourse :/

**Comment by michaelklishin** [comment]
I pushed a slightly modified version which I arrived at before this PR was amended. Thank you nonetheless.

**Pull request closed without merging**
