### PR TITLE
Clarify that action can update an entity

### PR DESCRIPTION
**Pull request by lukebakken**
See this `rabbitmq-users` discussion:

https://groups.google.com/d/topic/rabbitmq-users/8H50ivEe8nY/discussion

[168036494]

### CODE REVIEW

**Comment by michaelklishin** [comment]
This makes sense for limits but users have a separate update page (user name is a link!). I'm afraid renaming that form will make sure that no one ever navigates to the "Edit user" page. We have no real way to do an A/B test at a meaningful scale but I'd leave out the user form change.

**Comment by lukebakken** [comment]
If we don't change the submit button label we'll have to block updates from the "Add user" section ... is that what we want?

**Comment by lukebakken** [comment]
OK I will update the "Add user" page so that if a user is updated rather than created the popup reflects that. We can tell via the HTTP response code.

**Comment by michaelklishin** [comment]
Backported to `v3.7.x`.

**Pull request merged**
