### PR TITLE
Make healthchecks failures return an HTTP 500 instead of 200.

### LINKED ISSUE #840: Failed healthchecks return HTTP 200 status
The healthcheck APIs return a 200 response status even when the check has failed. This makes them harder to use as a 2xx response is generally considered a pass and a non-2xx a fail by most systems. These APIs should return a 500 response code on failure.

### PR DESCRIPTION
**Pull request by coderanger**
Fixes #840.

My Erlang is extremely rusty so this might be entirely the wrong way to do this, but I figured I would try.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@coderanger Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-management&pullRequestId=841)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-management&pullRequestId=841) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@coderanger Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-management&pullRequestId=841)!

**Comment by michaelklishin** [comment]
@essen is there are more typical way of returning a 500 response in modern Cowboy?

**Comment by essen** [comment]
It's a response like any other so `cowboy_req:reply` is the way to go.

**Comment by coderanger** [comment]
Is the way I'm calling it correct? Most of the examples were a lot simpler so I wasn't entirely certain if I plugged it all together correctly :)

**Comment by essen** [comment]
Assuming `Response` is the response body yes. Sorry I'm not available to check further at the moment.

**Comment by michaelklishin** [comment]
To reproduce a failure, use a very low timeout:

``` shell
curl -v -H "Accept:application/json" -H "timeout: 1" -u guest:guest "http://localhost:15672/api/healthchecks/node"
```

which will return

```
< HTTP/1.1 500 Internal Server Error
< cache-control: no-cache
< content-length: 38
< content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'
< content-type: application/json
< date: Wed, 09 Sep 2020 12:19:22 GMT
< server: Cowboy
< vary: accept, accept-encoding, origin
```

``` json
{
  "status": "failed",
  "reason": "timeout"
}
```

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request merged**
