### PR TITLE
Add a hack to properly return an empty JSON object for shovel

### PR DESCRIPTION
**Pull request by essen**
Part of proposal to fix https://github.com/rabbitmq/rabbitmq-management/issues/75 on stable

### CODE REVIEW

**Comment by michaelklishin** [comment]
This has conflicts, please resolve.

**Comment by essen** [comment]
Should be good. Sorry I didn't see the message earlier.

**Comment by michaelklishin** [comment]
@essen can you please look into a PR for master soon? we have a script that spams us if stable isn't merged into master in any of the repos. Thank you.

**Comment by essen** [comment]
The "fix" for master is the switch to a JSON library that uses maps. I started but am nowhere close to finish. You may also apply this patch to master directly (or I can add a PR with it) but that's basically a waste of time.

**Comment by michaelklishin** [comment]
We can merge stable into master and undo all the changes for now, then transition to a new shared JSON library. WDYT?

**Comment by essen** [comment]
Fine with me, just weird. :-)

**Pull request merged**
