### PR TITLE
Limit sample ranges sent to the client

### PR DESCRIPTION
**Pull request by essen**
Update: I did now. (I did not change the behavior that silently dropped ranges when the input is invalid. I can change that into a proper error if required.)

Fixes https://github.com/rabbitmq/rabbitmq-management/issues/97.

### CODE REVIEW

**Comment by essen** [comment]
I have pushed a commit that adds a test and changes the return value in queues resources when ranges are invalid.

However I now realize there are more places that make use of ranges and more changes and tests are required to cover all resources.

**Comment by essen** [comment]
OK I have added a try/catch everywhere applicable. I did not add a test everywhere applicable because it wouldn't test for much more than the test I added does (it would just test that the throw is catched). But I can add a test for every resource if you need me to.

**Comment by michaelklishin** [comment]
Yes, lets do that. Even if it's the same (fairly basic) test for every resource.

**Comment by essen** [comment]
On it!

**Comment by essen** [comment]
Done. And good call, because I had to fix a few things.

**Pull request merged**
