### PR TITLE
Allow for password_hash instead of password when declaring users

### PR DESCRIPTION
**Pull request by wishdev**
## Proposed Changes

This allows for the use of password_hash instead of password when declaring a user. Avoids having an actual password where not required.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the mailing list. We're here to help! This is simply a reminder
of what we are going to look for before merging your code._

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by hairyhum** [comment]
Hi.
Passwords can be hashed with different algorithms, which operators can [configure](https://www.rabbitmq.com/passwords.html#changing-algorithm) via conig file.

Should this API also include (maybe optional) `hashing_algorithm` key?

**Comment by michaelklishin** [comment]
@wishdev thank you. @hairyhum is correct, we cannot omit the algorithm and the test will only pass [with default configurations](http://www.rabbitmq.com/passwords.html).

I'll look into adding the algorithm field.

**Comment by wishdev** [comment]
I believe the test passes regardless of algorithm because the api only seems to care if the hash is a base64 string - the test string actually is not a valid SHA256 hash size but it passes anyways because it's a valid base64 string.

I did not see the algorithm listed here as an option for the HTTP API - https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.9/priv/www/api/index.html - would love to see it added if it can. I just wasn't aware it existed.

Thanks for any assistance you can offer....

**Comment by michaelklishin** [comment]
You are right, the test would pass because the algorithm is stored in the user record (this is something that had to be done for backwards compatibility).

There are tests that specify a hashing algorithm in the HTTP API test suite.

One more thing I found as I was testing my changes is that the change to how the mandatory arguments are declared leads to a confusing help message:

```
declare user name=... ['password', 'password_hash']=... tags=...
```

I'm looking into it.

**Comment by michaelklishin** [comment]
@wishdev please take a look at what I ended up with in `master`. Thank you for contributing!

**Comment by wishdev** [comment]
Looks amazing. I appreciate very much the assistance. I also value the patience with a less than perfect starting point :)

**Comment by lukebakken** [comment]
@wishdev we're always very happy when someone has both a good idea and some code to start with.

**Pull request merged**
